name: CI Hardhat

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'contracts/**'
      - 'test/**'
      - 'hardhat.config.js'
      - 'package.json'
      - 'scripts/**'
      - '.github/workflows/ci.yml'
  push:
    branches: [ chore/restructure-flowcash-cypherpunk ]
    paths:
      - 'contracts/**'
      - 'test/**'
      - 'hardhat.config.js'
      - 'package.json'
      - 'scripts/**'
      - '.github/workflows/ci.yml'

jobs:
  hardhat:
    name: Compile & Test (Hardhat)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run tests
        run: npx hardhat test
